#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  aop:
    auto: true
  jpa:
    show-sql: true
    open-in-view: false
    # https://stackoverflow.com/a/67678945/548473
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  datasource:
    # Embedded
    url: jdbc:h2:file:E:\Projects\PelikanStroy;MV_STORE=false;AUTO_SERVER=TRUE
    username: sa
    password: sa